// src/App.tsx
import React, { useState, useEffect } from "react";
import { FolderOpen, User } from "lucide-react";
import { documentDir } from "@tauri-apps/api/path";
import { settings } from "./tauri-store/settings";
import { path } from "@tauri-apps/api";
import "./App.css";
import {AuthProvider, AuthContextType, useAuth} from "./context/auth-context.tsx";
import {TrokkFilesProvider} from "./context/trokk-files-context.tsx";
import MainLayout from "./components/layouts/main-layout.tsx";
import Modal from "./components/ui/modal.tsx";
import SettingsForm from "./features/settings/settings.tsx";
import { UploadProgressProvider } from "./context/upload-progress-context.tsx";
import Button from "./components/ui/button.tsx";

function App() {
    const [scannerPath, setScannerPath] = useState<string>("");
    const [openSettings, setOpenSettings] = useState<boolean>(false);
    console.debug(import.meta.env.REACT_APP_SENTRY_URL);

    useEffect(() => {
        const initializeSettings = async () => {
            try {
                await settings.init();
                const savedScanPath = await settings.getScannerPath();
                if (savedScanPath) {
                    setScannerPath(savedScanPath);
                } else {
                    const defaultPath = await documentDir() + path.sep() + "trokk" + path.sep() + "files";
                    await settings.setScannerPath(defaultPath);
                    setScannerPath(defaultPath);
                }
            } catch (error) {
                console.error("Error initializing settings:", error);
            }
        };

        void initializeSettings();
    }, []);

    return (
        <AuthProvider>
            <main className="mainContainer">
                <Content
                    scannerPath={scannerPath}
                    openSettings={openSettings}
                    setOpenSettings={setOpenSettings}
                />
            </main>
            <Modal isOpen={openSettings} onClose={() => setOpenSettings(false)}>
                <SettingsForm />
            </Modal>
        </AuthProvider>
    );
}

interface ContentProps {
    scannerPath: string;
    openSettings: boolean;
    setOpenSettings: React.Dispatch<React.SetStateAction<boolean>>
}

const Content: React.FC<ContentProps> = ({ scannerPath, openSettings, setOpenSettings }) => {
    const { authResponse, loggedOut, isLoggingIn, fetchSecretsError, login, logout } = useAuth() as AuthContextType;

    if (fetchSecretsError) {
        return (
            <>
                <div className="topBar">
                    <p></p>
                    <h1>Trøkk</h1>
                    <p></p>
                </div>
                <div className="vaultError errorColor">
                    <h1>Feil ved innhenting av hemmeligheter</h1>
                    <p>{fetchSecretsError}</p>
                </div>
            </>
        );
    }

    if (loggedOut && !isLoggingIn) {
        return (
            <div className={`w-screen h-screen flex flex-col justify-center items-center text-center`}>
                <img alt={`Trøkk logo`} src="banner.png" className={`w-96 pb-10`}></img>
                <Button className={`w-[150px] h-[75px] text-2xl`} onClick={login}>Logg inn</Button>
            </div>
        );
    }

    if (isLoggingIn && !authResponse) {
        return (
            <div className={`w-screen h-screen flex flex-col justify-center items-center text-center`}>
                <img alt={`Trøkk logo`} src="banner.png" className={`w-96 pb-10`}></img>
                <h2 className={`h-[75px]`}>Nytt innloggingsvindu åpnet, vennligst logg inn der...</h2>
            </div>
        );
    }

    if (!authResponse) {
        return (
            <div className={`w-screen h-screen flex flex-col justify-center items-center text-center`}>
                <img alt={`Trøkk logo`} src="banner.png" className={`w-96 pb-10`}></img>
                <Button className={`w-[150px] h-[75px] text-2xl`} onClick={login}>Logg inn</Button>
            </div>
        );
    }

    return (
        <>
            <div className="grid grid-cols-3 mt-2 sticky top-0">
                <h2 className="text-xl flex items-center pl-4">
                    <FolderOpen size="32" className="-ml-3 mr-1 mb-2 flex-shrink-0"/>{scannerPath}
                </h2>
                <h1 className="text-4xl content-end">Trøkk</h1>
                <div className="flex justify-end gap-2">
                    <div className="flex pr-2 pt-3">
                        <User />
                        <p className="pt-0.5">{authResponse!!.userInfo.givenName}</p>
                    </div>
                    <Button onClick={() => setOpenSettings(!openSettings)}>Innstillinger</Button>
                    <Button onClick={logout}>Logg ut</Button>
                </div>
            </div>
            <TrokkFilesProvider scannerPath={scannerPath}>
                <UploadProgressProvider>
                    <MainLayout/>
                </UploadProgressProvider>
            </TrokkFilesProvider>
        </>
    );
};

export default App;

// src/App.svelte
<script lang="ts">
    import Files from './lib/Files.svelte';
    import Settings from './lib/Settings.svelte';
    import { onMount } from 'svelte';
    import { documentDir } from '@tauri-apps/api/path';
    import { settings } from './lib/util/settings';
    import Auth from './lib/Auth.svelte';
    import { User } from 'lucide-svelte';


    let scannerPath: string;
    let donePath: string;
    let useS3: boolean;

    let openSettings = false;

    let authComponent: Auth;
    let authResponse: AuthenticationResponse | null;
    let fetchSecretsError: string | null;
    let loggedOut: Boolean;

    onMount(async () => {
        settings.scannerPath.then(async (savedScanPath) => {
            if (savedScanPath) {
                scannerPath = savedScanPath;
            } else {
                let defaultPath = await documentDir() + 'trokk/files';
                settings.scannerPath = defaultPath;
                scannerPath = defaultPath;
            }
        });

        settings.donePath.then(async (savedDonePath) => {
            if (savedDonePath) {
                donePath = savedDonePath;
            } else {
                let defaultPath = await documentDir() + 'trokk/done';
                settings.donePath = defaultPath;
                donePath = defaultPath;
            }
        });

        settings.useS3.then(async (savedUseS3) => {
            if (savedUseS3 !== null) {
                useS3 = savedUseS3;
            } else {
                let defaultUseS3 = true;
                settings.useS3 = defaultUseS3;
                useS3 = defaultUseS3;
            }
        });
    });

    function handleNewSettings(event: CustomEvent) {
        const eventScannerPath = event.detail.newScanPath;
        if (eventScannerPath) {
            scannerPath = eventScannerPath;
            settings.scannerPath = eventScannerPath;
        }

        const eventDonePath = event.detail.newDonePath;
        if (eventDonePath) {
            donePath = eventDonePath;
            settings.donePath = eventDonePath;
        }

        const eventUseS3 = event.detail.newUseS3;
        if (eventUseS3 !== undefined) {
            useS3 = eventUseS3;
            settings.useS3 = eventUseS3;
        }
    }

</script>

<main class="mainContainer">
    <Auth bind:this={authComponent} bind:authResponse bind:loggedOut bind:fetchSecretsError></Auth>
    {#if fetchSecretsError}
        <div class="topBar">
            <p></p>
            <h1>Trøkk</h1>
            <p></p>
        </div>
        <div class="vaultError errorColor">
            <h1>Feil ved innhenting av hemmeligheter</h1>
            <p>{fetchSecretsError}</p>
        </div>
    {:else if authResponse}
        <div class="topBar">
            <p></p>
            <h1>Trøkk</h1>
            <div class="topRightMenu">
                <div>
                    <User />
                    <div>{authResponse.userInfo.givenName}</div>
                </div>
                <button on:click={() => openSettings = !openSettings}>Innstillinger</button>
                <button on:click={() => authComponent.logout()}>Logg ut</button>
            </div>
        </div>
        {#if openSettings}
            <Settings on:save={handleNewSettings}></Settings>
        {/if}
        <Files bind:scannerPath bind:useS3></Files>
    {:else if loggedOut}
        <div class="login">
            <button on:click={() => authComponent.login()}>Logg inn</button>
        </div>
    {:else}
        <h1>Trøkk</h1>
        <p>Logger inn...</p>
    {/if}
</main>


<style lang="scss">
  .mainContainer {
    display: flex;
    flex-direction: column;
  }

  .topRightMenu {
    display: flex;
    flex-direction: row;
    align-items: center;

    > div {
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-right: 10px;
    }

    > button {
      margin-left: 10px;
    }
  }

  .topBar {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    position: sticky;
    top: 0;
    height: 5vh;
  }

  .login {
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;

    > button {
      width: 200px;
      height: 100px;
      font-size: 30px;
    }
  }

  @media (prefers-color-scheme: dark) {
    .errorColor {
      background-color: #aa0000;
      color: white;
    }
  }

  @media (prefers-color-scheme: light) {
    .errorColor {
      background-color: #ff7373;
      color: black;
    }
  }

  .vaultError {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: max-content;
    align-self: center;
    border-radius: 5px;
    padding: 10px;
  }
</style>
